apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: DEPLOYMENTNAME
  labels:
    app: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      containers:
      - name: DEPLOYMENTNAME
       # need to fix this (and push) as cannot distinguish between dev, staging, live
        image: eu.gcr.io/cessda-development/cvmanager-gui:latest
        #image: eu.gcr.io/cessda-development/cessda/cessda.cvmanager:latest
        env:
        - name: DC_ENV
          value: ENVIRONMENT
        ports:
        - containerPort: 8080
          name: frontend-cport
        imagePullPolicy: Always
