apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: split-PVCNAME
  namespace: NAMESPACE
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: PVNAME