apiVersion: v1
kind: PersistentVolume
metadata:
  name: SPLIT-PVNAME
  namespace: NAMESPACE
  labels:
    name: PVNAME
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "DISKNAME"
