version: '2'
services:
  cvs-app:
    image: cvs
    volumes:
      - cvs-content:/content
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://cvs-mysql:3306/cvs
      - JHIPSTER_SLEEP=30   # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://cvs-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://cvs-elasticsearch:9200
    ports:
      - 8090:8080
  cvs-mysql:
    extends:
      file: mysql.yml
      service: cvs-mysql
  cvs-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: cvs-elasticsearch
volumes:
  cvs-content:
  cvs-es:
  cvs-dbs:
