version: '2'
services:
  cvs-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    volumes:
      - cvs-es:/usr/share/elasticsearch/data/
    ports:
      - 9203:9200
      - 9303:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
