version: '2'
services:
  cvs-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    volumes:
      - cvs-es:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
    command:
      - sh
      - -c
      - "./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu;
        /usr/local/bin/docker-entrypoint.sh elasticsearch"
